# Generated by Django 4.0.3 on 2022-04-04 13:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bought_ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('year', models.DateField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('path', models.FileField(upload_to='')),
                ('lang', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('sub_genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField(auto_now_add=True)),
                ('review', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebook_api.customer')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebook_api.ebook')),
            ],
        ),
        migrations.AddField(
            model_name='ebook',
            name='genre',
            field=models.ManyToManyField(to='ebook_api.genre'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bought_ebooks',
            field=models.ManyToManyField(through='ebook_api.bought_ebook', to='ebook_api.ebook'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bought_ebook',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebook_api.customer'),
        ),
        migrations.AddField(
            model_name='bought_ebook',
            name='ebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebook_api.ebook'),
        ),
        migrations.CreateModel(
            name='authored_ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebook_api.author')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebook_api.ebook')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='authored_ebooks',
            field=models.ManyToManyField(through='ebook_api.authored_ebook', to='ebook_api.ebook'),
        ),
    ]
